server:
  port: 9411
spring:
  application:
    name: cloud-zipkin-server
  main:
    allow-bean-definition-overriding: true
armeria:
  ports:
    - port: 9412
eureka:
      client:
        serviceUrl:
          defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
